// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package versionv3

import (
	"encoding/gob"

	"github.com/opendoor-labs/gozw/cc"
)

const CommandCapabilitiesGet cc.CommandID = 0x15

func init() {
	gob.Register(CapabilitiesGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x86),
		Command:      cc.CommandID(0x15),
		Version:      3,
	}, NewCapabilitiesGet)
}

func NewCapabilitiesGet() cc.Command {
	return &CapabilitiesGet{}
}

// <no value>
type CapabilitiesGet struct {
}

func (cmd CapabilitiesGet) CommandClassID() cc.CommandClassID {
	return 0x86
}

func (cmd CapabilitiesGet) CommandID() cc.CommandID {
	return CommandCapabilitiesGet
}

func (cmd CapabilitiesGet) CommandIDString() string {
	return "VERSION_CAPABILITIES_GET"
}

func (cmd *CapabilitiesGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *CapabilitiesGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
