// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package versionv3

import (
	"encoding/gob"

	"github.com/opendoor-labs/gozw/cc"
)

const CommandZwaveSoftwareGet cc.CommandID = 0x17

func init() {
	gob.Register(ZwaveSoftwareGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x86),
		Command:      cc.CommandID(0x17),
		Version:      3,
	}, NewZwaveSoftwareGet)
}

func NewZwaveSoftwareGet() cc.Command {
	return &ZwaveSoftwareGet{}
}

// <no value>
type ZwaveSoftwareGet struct {
}

func (cmd ZwaveSoftwareGet) CommandClassID() cc.CommandClassID {
	return 0x86
}

func (cmd ZwaveSoftwareGet) CommandID() cc.CommandID {
	return CommandZwaveSoftwareGet
}

func (cmd ZwaveSoftwareGet) CommandIDString() string {
	return "VERSION_ZWAVE_SOFTWARE_GET"
}

func (cmd *ZwaveSoftwareGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *ZwaveSoftwareGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
