// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package allclasses

import (
	"github.com/gozwave/gozw/cc/alarm"
	alarmv2 "github.com/gozwave/gozw/cc/alarm-v2"
	applicationstatus "github.com/gozwave/gozw/cc/application-status"
	"github.com/gozwave/gozw/cc/association"
	associationv2 "github.com/gozwave/gozw/cc/association-v2"
	"github.com/gozwave/gozw/cc/basic"
	basicv2 "github.com/gozwave/gozw/cc/basic-v2"
	"github.com/gozwave/gozw/cc/battery"
	"github.com/gozwave/gozw/cc/clock"
	"github.com/gozwave/gozw/cc/configuration"
	doorlock "github.com/gozwave/gozw/cc/door-lock"
	doorlocklogging "github.com/gozwave/gozw/cc/door-lock-logging"
	doorlockv2 "github.com/gozwave/gozw/cc/door-lock-v2"
	doorlockv3 "github.com/gozwave/gozw/cc/door-lock-v3"
	doorlockv4 "github.com/gozwave/gozw/cc/door-lock-v4"
	manufacturerspecific "github.com/gozwave/gozw/cc/manufacturer-specific"
	manufacturerspecificv2 "github.com/gozwave/gozw/cc/manufacturer-specific-v2"
	nodenaming "github.com/gozwave/gozw/cc/node-naming"
	notificationv3 "github.com/gozwave/gozw/cc/notification-v3"
	notificationv4 "github.com/gozwave/gozw/cc/notification-v4"
	notificationv5 "github.com/gozwave/gozw/cc/notification-v5"
	"github.com/gozwave/gozw/cc/security"
	sensorconfiguration "github.com/gozwave/gozw/cc/sensor-configuration"
	sensormultilevel "github.com/gozwave/gozw/cc/sensor-multilevel"
	sensormultilevelv10 "github.com/gozwave/gozw/cc/sensor-multilevel-v10"
	sensormultilevelv11 "github.com/gozwave/gozw/cc/sensor-multilevel-v11"
	sensormultilevelv2 "github.com/gozwave/gozw/cc/sensor-multilevel-v2"
	sensormultilevelv3 "github.com/gozwave/gozw/cc/sensor-multilevel-v3"
	sensormultilevelv4 "github.com/gozwave/gozw/cc/sensor-multilevel-v4"
	sensormultilevelv5 "github.com/gozwave/gozw/cc/sensor-multilevel-v5"
	sensormultilevelv6 "github.com/gozwave/gozw/cc/sensor-multilevel-v6"
	sensormultilevelv7 "github.com/gozwave/gozw/cc/sensor-multilevel-v7"
	sensormultilevelv8 "github.com/gozwave/gozw/cc/sensor-multilevel-v8"
	sensormultilevelv9 "github.com/gozwave/gozw/cc/sensor-multilevel-v9"
	switchall "github.com/gozwave/gozw/cc/switch-all"
	switchbinary "github.com/gozwave/gozw/cc/switch-binary"
	switchbinaryv2 "github.com/gozwave/gozw/cc/switch-binary-v2"
	switchcolor "github.com/gozwave/gozw/cc/switch-color"
	switchcolorv2 "github.com/gozwave/gozw/cc/switch-color-v2"
	switchcolorv3 "github.com/gozwave/gozw/cc/switch-color-v3"
	switchmultilevel "github.com/gozwave/gozw/cc/switch-multilevel"
	switchmultilevelv2 "github.com/gozwave/gozw/cc/switch-multilevel-v2"
	switchmultilevelv3 "github.com/gozwave/gozw/cc/switch-multilevel-v3"
	switchmultilevelv4 "github.com/gozwave/gozw/cc/switch-multilevel-v4"
	switchtogglebinary "github.com/gozwave/gozw/cc/switch-toggle-binary"
	thermostatfanmode "github.com/gozwave/gozw/cc/thermostat-fan-mode"
	thermostatfanmodev2 "github.com/gozwave/gozw/cc/thermostat-fan-mode-v2"
	thermostatfanmodev3 "github.com/gozwave/gozw/cc/thermostat-fan-mode-v3"
	thermostatfanmodev4 "github.com/gozwave/gozw/cc/thermostat-fan-mode-v4"
	thermostatfanstate "github.com/gozwave/gozw/cc/thermostat-fan-state"
	thermostatfanstatev2 "github.com/gozwave/gozw/cc/thermostat-fan-state-v2"
	thermostatmode "github.com/gozwave/gozw/cc/thermostat-mode"
	thermostatmodev2 "github.com/gozwave/gozw/cc/thermostat-mode-v2"
	thermostatmodev3 "github.com/gozwave/gozw/cc/thermostat-mode-v3"
	thermostatoperatingstate "github.com/gozwave/gozw/cc/thermostat-operating-state"
	thermostatsetpoint "github.com/gozwave/gozw/cc/thermostat-setpoint"
	thermostatsetpointv2 "github.com/gozwave/gozw/cc/thermostat-setpoint-v2"
	thermostatsetpointv3 "github.com/gozwave/gozw/cc/thermostat-setpoint-v3"
	"github.com/gozwave/gozw/cc/time"
	timev2 "github.com/gozwave/gozw/cc/time-v2"
	usercode "github.com/gozwave/gozw/cc/user-code"
	usercodev2 "github.com/gozwave/gozw/cc/user-code-v2"
	"github.com/gozwave/gozw/cc/version"
	versionv2 "github.com/gozwave/gozw/cc/version-v2"
	versionv3 "github.com/gozwave/gozw/cc/version-v3"
	wakeup "github.com/gozwave/gozw/cc/wake-up"
	wakeupv2 "github.com/gozwave/gozw/cc/wake-up-v2"
)

func init() {

	alarm.Noop()
	alarmv2.Noop()
	notificationv3.Noop()
	notificationv4.Noop()
	notificationv5.Noop()
	applicationstatus.Noop()
	association.Noop()
	associationv2.Noop()
	basic.Noop()
	basicv2.Noop()
	battery.Noop()
	clock.Noop()
	configuration.Noop()
	doorlocklogging.Noop()
	doorlock.Noop()
	doorlockv2.Noop()
	doorlockv3.Noop()
	doorlockv4.Noop()
	manufacturerspecific.Noop()
	manufacturerspecificv2.Noop()
	nodenaming.Noop()
	security.Noop()
	sensorconfiguration.Noop()
	sensormultilevel.Noop()
	sensormultilevelv2.Noop()
	sensormultilevelv3.Noop()
	sensormultilevelv4.Noop()
	sensormultilevelv5.Noop()
	sensormultilevelv6.Noop()
	sensormultilevelv7.Noop()
	sensormultilevelv8.Noop()
	sensormultilevelv9.Noop()
	sensormultilevelv10.Noop()
	sensormultilevelv11.Noop()
	switchall.Noop()
	switchbinary.Noop()
	switchbinaryv2.Noop()
	switchmultilevel.Noop()
	switchmultilevelv2.Noop()
	switchmultilevelv3.Noop()
	switchmultilevelv4.Noop()
	switchtogglebinary.Noop()
	thermostatfanmode.Noop()
	thermostatfanmodev2.Noop()
	thermostatfanmodev3.Noop()
	thermostatfanmodev4.Noop()
	thermostatfanstate.Noop()
	thermostatfanstatev2.Noop()
	thermostatmode.Noop()
	thermostatmodev2.Noop()
	thermostatmodev3.Noop()
	thermostatoperatingstate.Noop()
	thermostatsetpoint.Noop()
	thermostatsetpointv2.Noop()
	thermostatsetpointv3.Noop()
	time.Noop()
	timev2.Noop()
	usercode.Noop()
	usercodev2.Noop()
	version.Noop()
	versionv2.Noop()
	versionv3.Noop()
	wakeup.Noop()
	wakeupv2.Noop()
	switchcolor.Noop()
	switchcolorv2.Noop()
	switchcolorv3.Noop()
}

func Noop() {}
