// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package usercodev2

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandChecksumGet cc.CommandID = 0x11

func init() {
	gob.Register(ChecksumGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x63),
		Command:      cc.CommandID(0x11),
		Version:      2,
	}, NewChecksumGet)
}

func NewChecksumGet() cc.Command {
	return &ChecksumGet{}
}

// <no value>
type ChecksumGet struct {
}

func (cmd ChecksumGet) CommandClassID() cc.CommandClassID {
	return 0x63
}

func (cmd ChecksumGet) CommandID() cc.CommandID {
	return CommandChecksumGet
}

func (cmd ChecksumGet) CommandIDString() string {
	return "USER_CODE_CHECKSUM_GET"
}

func (cmd *ChecksumGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *ChecksumGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
