// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package usercodev2

import (
	"encoding/binary"
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandChecksumReport cc.CommandID = 0x12

func init() {
	gob.Register(ChecksumReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x63),
		Command:      cc.CommandID(0x12),
		Version:      2,
	}, NewChecksumReport)
}

func NewChecksumReport() cc.Command {
	return &ChecksumReport{}
}

// <no value>
type ChecksumReport struct {
	UserCodeChecksum uint16
}

func (cmd ChecksumReport) CommandClassID() cc.CommandClassID {
	return 0x63
}

func (cmd ChecksumReport) CommandID() cc.CommandID {
	return CommandChecksumReport
}

func (cmd ChecksumReport) CommandIDString() string {
	return "USER_CODE_CHECKSUM_REPORT"
}

func (cmd *ChecksumReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.UserCodeChecksum = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	return nil
}

func (cmd *ChecksumReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	{
		buf := make([]byte, 2)
		binary.BigEndian.PutUint16(buf, cmd.UserCodeChecksum)
		payload = append(payload, buf...)
	}

	return
}
