// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package usercodev2

import (
	"encoding/binary"
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandExtendedUserCodeSet cc.CommandID = 0x0B

func init() {
	gob.Register(ExtendedUserCodeSet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x63),
		Command:      cc.CommandID(0x0B),
		Version:      2,
	}, NewExtendedUserCodeSet)
}

func NewExtendedUserCodeSet() cc.Command {
	return &ExtendedUserCodeSet{}
}

// <no value>
type ExtendedUserCodeSet struct {
	NumberOfUserCodes byte

	Vg1 []ExtendedUserCodeSetVg1
}

type ExtendedUserCodeSetVg1 struct {
	UserIdentifier uint16

	UserIdStatus byte

	Properties1 struct {
		UserCodeLength byte
	}

	UserCode []byte
}

func (cmd ExtendedUserCodeSet) CommandClassID() cc.CommandClassID {
	return 0x63
}

func (cmd ExtendedUserCodeSet) CommandID() cc.CommandID {
	return CommandExtendedUserCodeSet
}

func (cmd ExtendedUserCodeSet) CommandIDString() string {
	return "EXTENDED_USER_CODE_SET"
}

func (cmd *ExtendedUserCodeSet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NumberOfUserCodes = payload[i]
	i++

	for i < len(payload) {

		if len(payload) <= i {
			return errors.New("slice index out of bounds")
		}

		userIdentifier := binary.BigEndian.Uint16(payload[i : i+2])
		i += 2

		if len(payload) <= i {
			return errors.New("slice index out of bounds")
		}

		userIdStatus := payload[i]
		i++

		if len(payload) <= i {
			return errors.New("slice index out of bounds")
		}

		var properties1 Properties1

		properties1.UserCodeLength = (payload[i] & 0x0F)

		i += 1

		if len(payload) <= i {
			return errors.New("slice index out of bounds")
		}

		{
			length := (payload[2+2]) & 0x0F
			cmd.UserCode = payload[i : i+int(length)]
			i += int(length)
		}

		vg1 := ExtendedUserCodeSetVg1{

			UserIdentifier: userIdentifier,

			UserIdStatus: userIdStatus,

			Properties1: properties1,

			UserCode: userCode,
		}
		cmd.Vg1 = append(cmd.Vg1, vg1)
	}

	return nil
}

func (cmd *ExtendedUserCodeSet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.NumberOfUserCodes)

	for _, vg := range cmd.Vg1 {

		{
			buf := make([]byte, 2)
			binary.BigEndian.PutUint16(buf, vg.UserIdentifier)
			payload = append(payload, buf...)
		}

		payload = append(payload, vg.UserIdStatus)

		{
			var val byte

			val |= (vg.Properties1.UserCodeLength) & byte(0x0F)

			payload = append(payload, val)
		}

		if vg.UserCode != nil && len(vg.UserCode) > 0 {
			payload = append(payload, vg.UserCode...)
		}

	}

	return
}
