// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package usercodev2

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandKeypadModeGet cc.CommandID = 0x09

func init() {
	gob.Register(KeypadModeGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x63),
		Command:      cc.CommandID(0x09),
		Version:      2,
	}, NewKeypadModeGet)
}

func NewKeypadModeGet() cc.Command {
	return &KeypadModeGet{}
}

// <no value>
type KeypadModeGet struct {
}

func (cmd KeypadModeGet) CommandClassID() cc.CommandClassID {
	return 0x63
}

func (cmd KeypadModeGet) CommandID() cc.CommandID {
	return CommandKeypadModeGet
}

func (cmd KeypadModeGet) CommandIDString() string {
	return "USER_CODE_KEYPAD_MODE_GET"
}

func (cmd *KeypadModeGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *KeypadModeGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
