// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package usercodev2

import (
	"encoding/gob"
	"errors"

	"github.com/opendoor-labs/gozw/cc"
)

const CommandKeypadModeReport cc.CommandID = 0x0A

func init() {
	gob.Register(KeypadModeReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x63),
		Command:      cc.CommandID(0x0A),
		Version:      2,
	}, NewKeypadModeReport)
}

func NewKeypadModeReport() cc.Command {
	return &KeypadModeReport{}
}

// <no value>
type KeypadModeReport struct {
	KeypadMode byte
}

func (cmd KeypadModeReport) CommandClassID() cc.CommandClassID {
	return 0x63
}

func (cmd KeypadModeReport) CommandID() cc.CommandID {
	return CommandKeypadModeReport
}

func (cmd KeypadModeReport) CommandIDString() string {
	return "USER_CODE_KEYPAD_MODE_REPORT"
}

func (cmd *KeypadModeReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.KeypadMode = payload[i]
	i++

	return nil
}

func (cmd *KeypadModeReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.KeypadMode)

	return
}
