// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package usercodev2

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandKeypadModeSet cc.CommandID = 0x08

func init() {
	gob.Register(KeypadModeSet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x63),
		Command:      cc.CommandID(0x08),
		Version:      2,
	}, NewKeypadModeSet)
}

func NewKeypadModeSet() cc.Command {
	return &KeypadModeSet{}
}

// <no value>
type KeypadModeSet struct {
	KeypadMode byte
}

func (cmd KeypadModeSet) CommandClassID() cc.CommandClassID {
	return 0x63
}

func (cmd KeypadModeSet) CommandID() cc.CommandID {
	return CommandKeypadModeSet
}

func (cmd KeypadModeSet) CommandIDString() string {
	return "USER_CODE_KEYPAD_MODE_SET"
}

func (cmd *KeypadModeSet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.KeypadMode = payload[i]
	i++

	return nil
}

func (cmd *KeypadModeSet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.KeypadMode)

	return
}
