// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package usercodev2

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandMasterCodeGet cc.CommandID = 0x0F

func init() {
	gob.Register(MasterCodeGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x63),
		Command:      cc.CommandID(0x0F),
		Version:      2,
	}, NewMasterCodeGet)
}

func NewMasterCodeGet() cc.Command {
	return &MasterCodeGet{}
}

// <no value>
type MasterCodeGet struct {
}

func (cmd MasterCodeGet) CommandClassID() cc.CommandClassID {
	return 0x63
}

func (cmd MasterCodeGet) CommandID() cc.CommandID {
	return CommandMasterCodeGet
}

func (cmd MasterCodeGet) CommandIDString() string {
	return "MASTER_CODE_GET"
}

func (cmd *MasterCodeGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *MasterCodeGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
